### ISSUE TITLE
No-break space will not work between text and image

### ISSUE THREAD

**Issue by bpugliese** [PASCOscientific/cpd-oxygen-framework#48]
The image below shows how I can't keep the bolded word "Digits" together with its icon using a no-break space (project: https://github.com/PASCOscientific/Code_Cooling_Breeze, page 5, step 10)
![image](https://user-images.githubusercontent.com/76796068/151599570-709ed24e-e4b1-4585-aa14-6aa6df84002c.png)

**Comment by jonathanhanna** [comment]
I'm working on this. On a side note, you're using the Capstone graphics for Digits and Line Graph instead of the SPARKvue graphics. Just an FYI.

**Comment by bpugliese** [comment]
Yikes thank you for catching that, I must have been asleep when I did those images. Something told me there’s something a little weird there but I didn’t see it so I ignored it. Thanks!!

-Barbara

**Comment by jonathanhanna** [comment]
Fixed in 907e6ca5c0d8a89ecd7a7eeab1e81539347d74e5. For some reason, the non-breaking space is not transferring to the HTML. I'll need to contact Oxygen support about that.

As a workaround, I added a new rule that prevents the breaks. To do this, you will need to wrap the content in a `<ph>` element  with an outputclass of `no-break`. For example:

`...panels to <ph  outputclass="no-break"><b>Digits</b> <image conkeyref="capstone_icons/digits"/></ph> displays and...`
